### ISSUE TITLE
RuntimeError: Minecraft server reply with code 500

### ISSUE THREAD

**Issue by OrilinZ** [PondWader/Mineflayer-Spectator#1]
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 350538.
Server started on port 3001

Traceback (most recent call last):
  File "/data/zhz_data/Voyager/run_skill.py", line 57, in <module>
    sub_goals = voyager.decompose_task(task=task)
  File "/data/zhz_data/Voyager/voyager/voyager.py", line 377, in decompose_task
    self.last_events = self.env.reset(
  File "/data/zhz_data/Voyager/voyager/env/bridge.py", line 156, in reset
    returned_data = self.check_process()
  File "/data/zhz_data/Voyager/voyager/env/bridge.py", line 100, in check_process
    raise RuntimeError(
RuntimeError: Minecraft server reply with code 500
(mc) zhz@zju-ESC8000A-E11:/data/zhz_data/Voyager$ python run_skill.py 
Loading Skill Manager from ./skill_library/trial1/skill
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 353188.
Server started on port 3001

Traceback (most recent call last):
  File "/data/zhz_data/Voyager/run_skill.py", line 57, in <module>
    sub_goals = voyager.decompose_task(task=task)
  File "/data/zhz_data/Voyager/voyager/voyager.py", line 377, in decompose_task
    self.last_events = self.env.reset(
  File "/data/zhz_data/Voyager/voyager/env/bridge.py", line 156, in reset
    returned_data = self.check_process()
  File "/data/zhz_data/Voyager/voyager/env/bridge.py", line 100, in check_process
    raise RuntimeError(
RuntimeError: Minecraft server reply with code 500

**Comment by PondWader** [comment]
It seems you're using voyager.
Was voyager working before you tried to add Mineflayer-Spectator?
What did you change to add Mineflayer-Spectator?

**Comment by OrilinZ** [comment]
Thank you, I will try this. I have anther question on whether this project can be used to save the bot-view videos

**Comment by PondWader** [comment]
Since this does not seem to have been an issue with Mineflayer-Spectator I'll close this. You could use something like replay mod whilst connected to the server for recording.
